# -*- coding: utf-8 -*-
"""OS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ODpyBgOgDGppYf2bvR4zYgI-An6icqmu
"""

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/OMBS.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("BubbleSort (Process) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/Bubblesort.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("BubbleSort (Thread) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/Mergesort.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("Mergesort (Process) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/OMMS.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("Mergesort (Thread) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/Insertionsort.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("InsertionSort (Process) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/OMIS.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("InsertionSort (Thread) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/Quicksort.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("Quicksort (Process) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/OMQS.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("QuickSort (Thread) ")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/OMSS.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("SelectionSort (Process)")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()

import numpy as np
import matplotlib.pyplot as plt


file = open("drive/MyDrive/OS/Selectionsort.txt")
numpy_array = np.loadtxt(file, delimiter=",")

x_array=[1,2,3,4,5,6,7,8,9,10]

plt.xlabel('Trial')
plt.ylabel('Time')
plt.title("SelectionSort (Thread)")
plt.plot(x_array,numpy_array)
plt.show()
plt.clf()